name = "flourite-workers"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2021-11-21"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
